# Configuración de Fly.io para desplegar la aplicación Django

app = "repuestossj"
primary_region = "eze"

[build]

[env]
  PORT = "8000"
  DJANGO_SETTINGS_MODULE = "ShortyShop.settings"
  DATABASE_URL = "sqlite:////code/db.sqlite3"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

[[vm]]
  size = "shared-cpu-1x"
